# ============================================================================
# Rakefile
# Copyright (c) 2026 Hodong Kim <hodong@nimfsoft.com>
# SPDX-License-Identifier: 0BSD
# ============================================================================

require "fileutils"
require "open3"
require "rbconfig"
require "shellwords"
require "tmpdir"

include FileUtils

SRC_TOP      = __dir__
PROJECT       = File.join(SRC_TOP, "adac.gpr")
INTERNAL_TEST_PROJECT =
  File.join(SRC_TOP, "tests-internal", "adac_internal_tests.gpr")
TEST_RUNNER_PROJECT =
  File.join(SRC_TOP, "tests-runner", "adac_test_runner.gpr")
CLAIR_ROOT = File.expand_path("../clair", SRC_TOP)
CLAIR_RAKEFILE = File.join(CLAIR_ROOT, "Rakefile")
BUILD_ROOT  = "build"

SUPPORTED_TARGET_OS = %w[freebsd linux darwin windows android].freeze
SUPPORTED_PROFILES  = %w[debug release].freeze

def fail_config(message)
  abort "ERROR: #{message}"
end

def env_choice(primary, alias_name = nil, default = nil)
  primary_value = ENV[primary]
  alias_value   = alias_name ? ENV[alias_name] : nil

  if primary_value && alias_value && primary_value != alias_value
    fail_config "#{primary} and #{alias_name} disagree"
  end

  primary_value || alias_value || default
end

def command_words(value)
  words = Shellwords.split(value.to_s)
  fail_config "empty command" if words.empty?
  words
end

def native_backend_supported?(target_arch, target_os)
  target_arch == "x86_64" && %w[freebsd linux].include?(target_os)
end

def ada_string_literal(value)
  text = value.to_s

  if text.match?(/[[:cntrl:]]/)
    fail_config "target metadata contains control characters"
  end

  %Q{"#{text.gsub('"', '""')}"}
end

def build_config_source
  native_backend_supported =
    if native_backend_supported?(TARGET_ARCH, TARGET_OS)
      "True"
    else
      "False"
    end

  <<~ADA
    -- ============================================================================
    -- adac-build_config.ads
    -- Generated by Rakefile. Do not edit.
    -- SPDX-License-Identifier: 0BSD
    -- ============================================================================

    package Adac.Build_Config is

      COMPILER_TARGET : constant String
                      := #{ada_string_literal(TARGET)};
      COMPILER_TARGET_ARCH : constant String
                           := #{ada_string_literal(TARGET_ARCH)};
      COMPILER_TARGET_OS : constant String
                         := #{ada_string_literal(TARGET_OS)};
      NATIVE_BACKEND_SUPPORTED : constant Boolean
                               := #{native_backend_supported};

    end Adac.Build_Config;
  ADA
end

def generate_build_config
  content = build_config_source

  mkdir_p GENERATED_SOURCE_DIR
  return if File.file?(BUILD_CONFIG_PATH) &&
            File.binread(BUILD_CONFIG_PATH) == content

  File.binwrite(BUILD_CONFIG_PATH, content)
end

def capture_command(*command)
  stdout, stderr, status = Open3.capture3(*command)
  return stdout.strip if status.success?

  fail_config "command failed: #{command.join(' ')}\n#{stderr}"
end

def find_program(name)
  return name if name.include?(File::SEPARATOR) && File.executable?(name)

  ENV.fetch("PATH", "").split(File::PATH_SEPARATOR).each do |dir|
    path = File.join(dir, name)
    return path if File.executable?(path)
  end

  nil
end

def infer_target_os(target)
  value = target.to_s.downcase

  return "android" if value.include?("android")
  return "freebsd" if value.include?("freebsd")
  return "linux"   if value.include?("linux")
  return "darwin"  if value.include?("darwin") || value.include?("apple")
  return "windows" if value.include?("mingw") ||
                      value.include?("windows") ||
                      value.include?("win32")

  nil
end

def normalize_target_os(value)
  return nil if value.nil?

  os = infer_target_os(value) || value.downcase
  return os if SUPPORTED_TARGET_OS.include?(os)

  nil
end

def infer_arch(target)
  arch = target.to_s.split("-").first.to_s.downcase

  case arch
  when "amd64"
    "x86_64"
  when "arm64"
    "aarch64"
  else
    arch
  end
end

def os_version(target, target_os)
  pattern = /#{Regexp.escape(target_os)}([0-9][0-9.]*)?/
  match = target.to_s.downcase.match(pattern)
  return nil unless match

  match[1]
end

def target_abi(target, target_os)
  value = target.to_s.downcase

  case target_os
  when "linux"
    return "musl"     if value.include?("musl")
    return "uclibc"   if value.include?("uclibc")
    return "gnueabihf" if value.include?("gnueabihf")
    return "gnueabi"  if value.include?("gnueabi")
    return "gnu"      if value.include?("gnu")

    # Most Linux compiler triples that omit the libc token still mean glibc.
    "gnu"
  when "windows"
    return "msvc"  if value.include?("msvc")
    return "mingw" if value.include?("mingw") ||
                      value.include?("w64") ||
                      value.include?("gnu")

    "windows"
  else
    "native"
  end
end

def native_target?(host_target, target, host_os, target_os, host_arch,
                   target_arch)
  return false unless host_os == target_os
  return false unless host_arch == target_arch

  case target_os
  when "freebsd", "darwin"
    host_version = os_version(host_target, host_os)
    target_version = os_version(target, target_os)

    target_version.nil? || host_version == target_version
  else
    target_abi(host_target, host_os) == target_abi(target, target_os)
  end
end

host_target = env_choice("ADAC_HOST_TARGET")

unless host_target
  host_cc = env_choice("ADAC_HOST_CC", nil,
                       ENV["CC"] || find_program("cc") ||
                       find_program("gcc"))

  host_target =
    if host_cc
      capture_command(*(command_words(host_cc) + ["-dumpmachine"]))
    else
      RbConfig::CONFIG["host"]
    end
end

HOST_TARGET = host_target

fail_config "cannot infer host target; set ADAC_HOST_TARGET" \
  if HOST_TARGET.to_s.empty?

HOST_OS = infer_target_os(HOST_TARGET) ||
          infer_target_os(RbConfig::CONFIG.fetch("host_os", ""))
HOST_ARCH = infer_arch(HOST_TARGET)

fail_config "cannot infer host OS from #{HOST_TARGET.inspect}" unless HOST_OS

HOST_ABI = target_abi(HOST_TARGET, HOST_OS)

TARGET = env_choice("ADAC_TARGET", "TARGET", HOST_TARGET)
TARGET_ARCH = infer_arch(TARGET)

inferred_target_os = infer_target_os(TARGET)
explicit_target_os_value = env_choice("ADAC_TARGET_OS", "OS")
explicit_target_os = normalize_target_os(explicit_target_os_value)

if explicit_target_os_value && explicit_target_os.nil?
  fail_config "unsupported target OS: #{explicit_target_os_value}"
end

if explicit_target_os && inferred_target_os &&
   explicit_target_os != inferred_target_os
  fail_config "ADAC_TARGET_OS=#{explicit_target_os} conflicts with " \
              "ADAC_TARGET=#{TARGET}"
end

TARGET_OS = explicit_target_os || inferred_target_os
fail_config "cannot infer target OS from #{TARGET.inspect}; set ADAC_TARGET_OS" \
  unless TARGET_OS
fail_config "unsupported target OS: #{TARGET_OS}" \
  unless SUPPORTED_TARGET_OS.include?(TARGET_OS)
TARGET_ABI = target_abi(TARGET, TARGET_OS)

profile_value = env_choice("ADAC_BUILD_PROFILE", "PROFILE")
if profile_value && ENV["BUILD"] && profile_value != ENV["BUILD"]
  fail_config "ADAC_BUILD_PROFILE/PROFILE and BUILD disagree"
end

BUILD_PROFILE = profile_value || ENV["BUILD"] || "release"
fail_config "unsupported build profile: #{BUILD_PROFILE}" \
  unless SUPPORTED_PROFILES.include?(BUILD_PROFILE)

NATIVE_TARGET = native_target?(HOST_TARGET, TARGET, HOST_OS, TARGET_OS,
                               HOST_ARCH, TARGET_ARCH)

GPR_TARGET = env_choice(
  "ADAC_GPR_TARGET",
  "GPR_TARGET",
  NATIVE_TARGET ? nil : TARGET
)

GPRBUILD = command_words(ENV["GPRBUILD"] || "gprbuild -j0")
GPRCLEAN = command_words(ENV["GPRCLEAN"] || "gprclean")
GPRLS    = command_words(ENV["GPRLS"] || "gprls")

TARGET_OBJ_DIR = File.join(BUILD_ROOT, "obj", TARGET, BUILD_PROFILE)
TARGET_BIN_DIR = File.join(BUILD_ROOT, "bin", TARGET, BUILD_PROFILE)
GENERATED_SOURCE_DIR =
  File.join(BUILD_ROOT, "generated", TARGET, BUILD_PROFILE)
BUILD_CONFIG_PATH =
  File.join(GENERATED_SOURCE_DIR, "adac-build_config.ads")
TARGET_EXE_EXT = TARGET_OS == "windows" ? ".exe" : ""

ADAC_EXE       = File.join(TARGET_BIN_DIR, "adac#{TARGET_EXE_EXT}")
ADAC_INTERNAL_TEST_EXE =
  File.join(TARGET_BIN_DIR, "adac-internal-tests#{TARGET_EXE_EXT}")
ADAC_TEST_RUNNER_EXE =
  File.join(TARGET_BIN_DIR, "adac-test-runner#{TARGET_EXE_EXT}")
INTERNAL_TEST_OBJ_DIR = File.join(TARGET_OBJ_DIR, "internal-tests")
TEST_RUNNER_OBJ_DIR   = File.join(TARGET_OBJ_DIR, "test-runner")
TEST_WORK_PARENT = File.join(BUILD_ROOT, "tests", TARGET, BUILD_PROFILE)

# Bypasses Rake's default task resolution for undefined arguments,
# enabling custom CLI parameter passing (e.g. `rake plat src`).
ARGV.drop(1).each do |arg|
  task arg.to_sym do; end unless Rake::Task.task_defined?(arg)
end

def gpr_switches(project = PROJECT)
  switches = []
  switches << "--target=#{GPR_TARGET}" if GPR_TARGET
  switches << "-XADAC_TARGET=#{TARGET}"
  switches << "-XADAC_TARGET_OS=#{TARGET_OS}"
  switches << "-XADAC_BUILD_PROFILE=#{BUILD_PROFILE}"
  switches << "-XADAC_GENERATED_SOURCE_DIR=#{GENERATED_SOURCE_DIR}"

  if project == TEST_RUNNER_PROJECT
    switches << "-XCLAIR_TARGET=#{TARGET}"
    switches << "-XCLAIR_TARGET_OS=#{TARGET_OS}"
    switches << "-XCLAIR_BUILD_PROFILE=#{BUILD_PROFILE}"
  end

  switches << "-P"
  switches << project
  switches
end

def require_project_source_exclusion!(project, source)
  mkdir_p GENERATED_SOURCE_DIR
  stdout, stderr, status =
    Open3.capture3(*(GPRBUILD + gpr_switches(project) + [source]))
  expected = %Q{"#{source}" was not found in the sources of any project}
  output = stdout + stderr

  return if !status.success? && output.include?(expected)

  fail_config "#{File.basename(project)} unexpectedly includes #{source} or failed " \
              "for a different reason:\n#{output}"
end

def bootstrap_profile_sources
  stdout, stderr, status =
    Open3.capture3(*(GPRLS + gpr_switches + ["--closure"]))
  unless status.success?
    fail_config "failed to resolve adac.gpr main closure:\n#{stdout}#{stderr}"
  end

  tracked_output, tracked_error, tracked_status =
    Open3.capture3("git", "-C", SRC_TOP, "ls-files", "-z")
  unless tracked_status.success?
    fail_config "failed to enumerate tracked sources:\n#{tracked_error}"
  end

  tracked = {}
  tracked_output.split("\0").each do |relative|
    next unless relative.end_with?(".ads", ".adb")

    tracked[File.expand_path(relative, SRC_TOP)] = relative
  end

  sources = stdout.lines.filter_map do |line|
    absolute = line.strip
    next unless absolute.end_with?(".ads", ".adb")

    tracked[File.expand_path(absolute)]
  end
  sources = sources.uniq.sort
  fail_config "adac.gpr tracked main closure is empty" if sources.empty?
  sources
end

def write_bootstrap_profile_manifest(path)
  sources = bootstrap_profile_sources
  File.write(path, sources.join("\n") + "\n")
end

def ensure_native_task!(task_name)
  return if NATIVE_TARGET

  fail_config "#{task_name} requires a native target; " \
              "use `rake build TARGET=#{TARGET}` for cross compilation"
end

def build_compiler
  mkdir_p [TARGET_OBJ_DIR, TARGET_BIN_DIR, GENERATED_SOURCE_DIR]
  generate_build_config
  sh(*(GPRBUILD + gpr_switches))
end

def build_internal_tests
  mkdir_p [INTERNAL_TEST_OBJ_DIR, TARGET_BIN_DIR]
  sh(*(GPRBUILD + gpr_switches(INTERNAL_TEST_PROJECT)))
end

def build_clair_dependency
  unless File.file?(CLAIR_RAKEFILE)
    fail_config "missing Clair build driver: #{CLAIR_RAKEFILE}"
  end

  environment = {
    "CLAIR_TARGET" => TARGET,
    "CLAIR_TARGET_OS" => TARGET_OS,
    "CLAIR_BUILD_PROFILE" => BUILD_PROFILE
  }
  environment["CLAIR_GPR_TARGET"] = GPR_TARGET if GPR_TARGET

  Dir.chdir(CLAIR_ROOT) do
    sh environment, "rake", "build"
  end
end

def build_test_runner
  mkdir_p [TEST_RUNNER_OBJ_DIR, TARGET_BIN_DIR]
  sh(*(GPRBUILD + gpr_switches(TEST_RUNNER_PROJECT)))
end

def clean_project
  generate_build_config

  unless NATIVE_TARGET
    puts "Skipping gprclean for non-native target #{TARGET}"
    return
  end

  compiler_was_built =
    File.exist?(ADAC_EXE) ||
    !Dir.glob(File.join(TARGET_OBJ_DIR, "adac_main.*")).empty?

  sh(*(GPRCLEAN + gpr_switches)) if compiler_was_built
ensure
  rm_rf GENERATED_SOURCE_DIR
end

desc "Show resolved host, target, and build directories"
task :info do
  puts "HOST_TARGET=#{HOST_TARGET}"
  puts "HOST_OS=#{HOST_OS}"
  puts "HOST_ABI=#{HOST_ABI}"
  puts "ADAC_TARGET=#{TARGET}"
  puts "ADAC_TARGET_ARCH=#{TARGET_ARCH}"
  puts "ADAC_TARGET_OS=#{TARGET_OS}"
  puts "ADAC_TARGET_ABI=#{TARGET_ABI}"
  puts "ADAC_BUILD_PROFILE=#{BUILD_PROFILE}"
  puts "NATIVE_TARGET=#{NATIVE_TARGET}"
  puts "NATIVE_BACKEND_SUPPORTED=" \
       "#{native_backend_supported?(TARGET_ARCH, TARGET_OS)}"
  puts "GPR_TARGET=#{GPR_TARGET}" if GPR_TARGET
  puts "OBJECT_DIR=#{TARGET_OBJ_DIR}"
  puts "EXEC_DIR=#{TARGET_BIN_DIR}"
  puts "GENERATED_SOURCE_DIR=#{GENERATED_SOURCE_DIR}"
  puts "CLAIR_ROOT=#{CLAIR_ROOT}"
end

desc "Test native backend target support rules"
task :"target-config-test" do
  cases = [
    ["x86_64", "freebsd", true],
    ["x86_64", "linux", true],
    ["aarch64", "freebsd", false],
    ["aarch64", "linux", false],
    ["x86_64", "darwin", false],
    ["x86_64", "windows", false],
    ["x86_64", "android", false]
  ]

  cases.each do |target_arch, target_os, expected|
    actual = native_backend_supported?(target_arch, target_os)
    next if actual == expected

    abort "unexpected native backend support for " \
          "#{target_arch}-#{target_os}: #{actual}"
  end
end

task default: :build

desc "Verify compiler GPR source ownership boundaries"
task :"project-boundary-test" do
  require_project_source_exclusion!(PROJECT, "adac_internal_tests.adb")
  require_project_source_exclusion!(PROJECT, "adac_test_runner.adb")
end

desc "Build only the adac compiler for the selected target"
task :"build-compiler" do
  build_compiler
end

desc "Build adac for the selected target"
task build: [:"build-compiler"]

desc "Run the native adac executable"
task :run do
  ensure_native_task!("run")
  Rake::Task[:"build-compiler"].invoke
  sh ADAC_EXE
end

desc "Run all test fixtures through Clair.Test"
task :test do
  ensure_native_task!("test")
  Rake::Task[:build].invoke
  build_internal_tests
  build_clair_dependency
  build_test_runner

  mkdir_p TEST_WORK_PARENT
  test_work_root = Dir.mktmpdir("run-", TEST_WORK_PARENT)
  test_succeeded = false

  begin
    bootstrap_profile_manifest =
      File.join(test_work_root, "bootstrap-profile-sources.txt")
    write_bootstrap_profile_manifest(bootstrap_profile_manifest)

    test_env = {
      "ADAC_TEST_ROOT" => File.expand_path(SRC_TOP),
      "ADAC_TEST_WORK_ROOT" => File.expand_path(test_work_root),
      "ADAC_TEST_COMPILER_EXECUTABLE" => File.expand_path(ADAC_EXE),
      "ADAC_TEST_INTERNAL_EXECUTABLE" =>
        File.expand_path(ADAC_INTERNAL_TEST_EXE),
      "ADAC_TEST_EXECUTABLE_EXTENSION" => TARGET_EXE_EXT,
      "ADAC_BOOTSTRAP_PROFILE_FILE" =>
        File.expand_path(bootstrap_profile_manifest)
    }

    sh test_env, ADAC_TEST_RUNNER_EXE
    test_succeeded = true
  ensure
    if test_succeeded
      rm_rf test_work_root
    else
      warn "Test artifacts retained at #{File.expand_path(test_work_root)}"
    end
  end
end

desc "Run all native checks"
task check: [:"target-config-test", :"project-boundary-test", :test]

desc "Remove generated files for the selected target/profile"
task :clean do
  clean_project

  rm_f "main.s"

  rm_rf TEST_WORK_PARENT
  rm_rf [TARGET_OBJ_DIR, TARGET_BIN_DIR]
end

desc "Remove all build directories, including legacy obj/bin"
task clobber: :clean do
  rm_rf BUILD_ROOT
  rm_rf ["obj", "bin"]
end

desc "Aggregates specified directories or files into a single output text file."
task :plat do
  targets = ARGV.drop(1)
  abort "Usage: rake plat <target1> [target2 ...]" if targets.empty?

  stamp = Time.now.strftime("%Y-%m-%d-%H-%M-%S")
  output = "#{stamp}.txt"

  files = targets.flat_map do |t|
    if File.file?(t)
      t
    elsif File.directory?(t)
      Dir.glob("#{t}/**/*").select { |f| File.file?(f) }
    else
      puts "Warning: Target not found or invalid - #{t}"
      []
    end
  end.uniq

  abort "No files found in #{targets.join(', ')}." if files.empty?

  File.open(output, "w") do |f|
    files.each do |path|
      f.puts "=" * 80
      f.puts "File: #{path}"
      f.puts "=" * 80
      begin
        f.puts File.read(path)
      rescue => e
        f.puts "-- I/O Error: #{e.message} --"
      end
      f.puts "\n\n"
    end
  end

  puts "Aggregation complete: #{output}"

  # Prevents Rake from treating following arguments as tasks.
  exit 0
end

task rebuild: [:clean, :build]
