package body Parent.Child is
  function Wrap (value : Integer) return Integer is
    procedure Touch is
      local : Integer;
    begin
      Helper.Call;
      declare
      begin
        declare
        begin
          declare
          begin
            declare
            begin
              declare
              begin
                declare
                begin
                  declare
                  begin
                    declare
                    begin
                      declare
                      begin
                        declare
                        begin
                          declare
                          begin
                            declare
                            begin
                              declare
                              begin
                                declare
                                begin
                                  declare
                                  begin
                                    declare
                                    begin
                                      declare
                                      begin
                                        declare
                                        begin
                                          declare
                                          begin
                                            declare
                                            begin
                                              declare
                                              begin
                                                declare
                                                begin
                                                  declare
                                                  begin
                                                    declare
                                                    begin
                                                      declare
                                                      begin
                                                        declare
                                                        begin
                                                          declare
                                                          begin
                                                            declare
                                                            begin
                                                              declare
                                                              begin
                                                                declare
                                                                begin
                                                                  declare
                                                                  begin
                                                                    declare
                                                                    begin
                                                                      declare
                                                                      begin
                                                                        declare
                                                                        begin
                                                                          declare
                                                                          begin
                                                                            declare
                                                                            begin
                                                                              declare
                                                                              begin
                                                                                declare
                                                                                begin
                                                                                  declare
                                                                                  begin
                                                                                    declare
                                                                                    begin
                                                                                      declare
                                                                                      begin
                                                                                        declare
                                                                                        begin
                                                                                          declare
                                                                                          begin
                                                                                            declare
                                                                                            begin
                                                                                              declare
                                                                                              begin
                                                                                                declare
                                                                                                begin
                                                                                                  declare
                                                                                                  begin
                                                                                                    declare
                                                                                                    begin
                                                                                                      declare
                                                                                                      begin
                                                                                                        declare
                                                                                                        begin
                                                                                                          declare
                                                                                                          begin
                                                                                                            declare
                                                                                                            begin
                                                                                                              declare
                                                                                                              begin
                                                                                                                declare
                                                                                                                begin
                                                                                                                  declare
                                                                                                                  begin
                                                                                                                    declare
                                                                                                                    begin
                                                                                                                      declare
                                                                                                                      begin
                                                                                                                        declare
                                                                                                                        begin
                                                                                                                          declare
                                                                                                                          begin
                                                                                                                            declare
                                                                                                                            begin
                                                                                                                              declare
                                                                                                                              begin
                                                                                                                                declare
                                                                                                                                begin
                                                                                                                                  declare
                                                                                                                                  begin
                                                                                                                                    declare
                                                                                                                                    begin
                                                                                                                                      local := value;
                                                                                                                                    end;
                                                                                                                                  end;
                                                                                                                                end;
                                                                                                                              end;
                                                                                                                            end;
                                                                                                                          end;
                                                                                                                        end;
                                                                                                                      end;
                                                                                                                    end;
                                                                                                                  end;
                                                                                                                end;
                                                                                                              end;
                                                                                                            end;
                                                                                                          end;
                                                                                                        end;
                                                                                                      end;
                                                                                                    end;
                                                                                                  end;
                                                                                                end;
                                                                                              end;
                                                                                            end;
                                                                                          end;
                                                                                        end;
                                                                                      end;
                                                                                    end;
                                                                                  end;
                                                                                end;
                                                                              end;
                                                                            end;
                                                                          end;
                                                                        end;
                                                                      end;
                                                                    end;
                                                                  end;
                                                                end;
                                                              end;
                                                            end;
                                                          end;
                                                        end;
                                                      end;
                                                    end;
                                                  end;
                                                end;
                                              end;
                                            end;
                                          end;
                                        end;
                                      end;
                                    end;
                                  end;
                                end;
                              end;
                            end;
                          end;
                        end;
                      end;
                    end;
                  end;
                end;
              end;
            end;
          end;
        end;
      end;
    end Touch;
  begin
    return value;
  end Wrap;
end Parent.Child;
